name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '45 23 * * 1,5'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: openvpn-ivpn

jobs:
  build:

    strategy:
      matrix:
        registry: [ghcr.io, docker.io]
        
        include:
          - registry: ghcr.io
            REPOSITORY: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USERNAME: ${{ github.actor }}
          
          - registry: docker.io
            REPOSITORY: egladman/${{ env.IMAGE_NAME }}
            TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
            USERNAME: egladman

    env:
      REGISTRY: ${{ matrix.registry }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.TOKEN }}

      - name: Build image
        run: make image TAG=${{ github.sha }} REPOSITORY=${{ env.REPOSITORY }} REPOSITORY_PREFIX=${{ env.REGISTRY }} DOCKER_BUILD_FLAGS="--build-arg SKIP_CHECKSUM=1"
  
      - name: Push image
        run: docker image push --all-tags ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
        if: ${{ github.event_name != 'pull_request' }}

